steps:
- name: node:16.9.0
  entrypoint: npm
  args: ["install"]
- name: node:16.9.0
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'MYSQL_HOST=${_MYSQL_HOST}'
    - 'MYSQL_USER=${_MYSQL_USER}'
    - 'MYSQL_DATABASE=${_MYSQL_DATABASE}'
    - 'MYSQL_PASSWORD=${_MYSQL_PASSWORD}'
    - 'JWT_SECRET=${_JWT_SECRET}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy","~/config/app.yaml"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/menhela/locations/asia-east1/workerPools/menhela-build'